orgnc/wordpress-plugin

Empire/AdConfigSyncCommand.php
Empire/AdminSettings.php
Empire/AmpAdsInjector.php
Empire/Empire.php
Empire/PageInjection.php
Empire/SDK/EmpireSdk.php
composer.json
composer.lock
empire.php

What's done:
- Fetching of ampConfig and adsConfig from EP and storing them in DB
- Implemented AMP "sanitizer" to inject Ads before optimizations from AMP plugging started
- Support for multiple selectors and placing limits
- Support of ad-blocking rules
- Injection of targeting information in ad components
- Support for different `relative` options
Note: this PR intentionally doesn't include `vendor/` dir to ease the review - I will commit dependencies at the end

AMP Ads Integration

---

Empire/AdminSettings.php

The `NOT EXISTS` query is far too slow to run on a web page load, which is breaking WeAreTheMighty.com.
This removes the reliance on that query in the Empire Settings page

Fix performance issue with Settings page

---

Empire/PageInjection.php

Creating this as a draft until the dependencies are deployed in Empire Platform

Upgrade Prebid Version

---

Empire/Empire.php

Wordpress stores titles html quoted in DB. Unquote titles before sending.

Export unquoted content titles

---

Empire/AdminSettings.php
Empire/ContentSyncCommand.php
Empire/Empire.php

Extracted from: #20
```bash
$ wp --debug=empire empire_sync_content --full --sleep-between=1 --batch-size=100
```

EP-883: full re-sync of posts data

---

Empire/Empire.php

* ensure that it is stored as an integer even when empty
This error was manifesting in the GraphQL endpoint as:
```
Return value of Empire\\Empire::getEmpirePixelTestPercent() must be of the type int, string returned
```

Fix type error with pixel test percentage

---

Organic/PageInjection.php
README.md

This change will not affect the production environment since the WordPress `apply_filters` function returns the 2nd parameter value when there isn't any place calling the filter. 
I'm implementing a new page template on the Empire theme where should not inject ads. So, the theme will use this filter to overlay the plugin ads injection settings on this template.

SWP: New Blank Page

---

Organic/GraphQL.php

I add 1 more field to expose the raw rules to GraphQL
Example results:

Expose the raw Ads rules to GraphQL

---

Organic/PageInjection.php

**Change Request:**
1. Adding functionality to AB test against AdThrive plugin. 
2. Based on the bucketing values, the plugin should initialize AdThrive script load or load Organic Ad scripts.
3. AB testing key should contain `%organic_adthrive%` for this to run else, Organic scripts will load as usual.
4. Dynamically loading `gpt.js` to prevent multiple google tag script load while testing with other Ad Wordpress plugins.
**Dependencies:**
1. AdThrive Plugin needs to be updated. IIFE that loads ad scripts in file `adthrive-ads/components/ads/partials/ads.php` need to declared as a function. example:
```
<script>
window.loadAdThrive = (function(w, d) {
w.adthrive = w.adthrive || {};
w.adthrive.cmd = w.adthrive.cmd || [];
w.adthrive.plugin = 'adthrive-ads-<?php echo esc_js( …
```

EP-1937: Adding functionality to initialize AdThrive code injection, if in the correct bucket. 

---

Organic/PageInjection.php

Adding another check for `organicTestKey` undefined value.

EP-1937: undefined organicTestKey check

---

Organic/PageInjection.php

* `if the search for a <p> tag fails, find a <span> instead`

Connatix Injector fails in some old WP instances

---

Organic/AdminSettings.php
Organic/Organic.php

This is intended to be used only for the initial synchronization batch since some sites are intentionally configured with no CRON mechanism to run in the background.

Adding manual sync method for sites without cron

---

Organic/AdConfigSyncCommand.php
Organic/AdminNotice.php
Organic/AdminSettings.php
Organic/AdsConfig.php
Organic/AdsInjector.php
Organic/AdsTxtSyncCommand.php
Organic/AmpAdsInjector.php
Organic/AmpConfig.php
Organic/BaseConfig.php
Organic/CCPAPage.php
Organic/ContentIdMapSyncCommand.php
Organic/ContentSyncCommand.php
Organic/Environment.php
Organic/FbiaAdsInjector.php
Organic/FbiaConfig.php
Organic/FbiaProxy.php
Organic/GraphQL.php
Organic/Organic.php
Organic/PageInjection.php
Organic/PrefillAdsInjector.php
Organic/PrefillConfig.php
Organic/SDK/OrganicSdk.php
Organic/public.php
composer.json
composer.lock
phpcs.xml

Some users reported issues with PHP 7.2, so reducing requirements to PHP 7.0 to expand compatibility with user Wordpress installations.

Removing non-backward compatible PHP annotations

---

Organic/AdminSettings.php
Organic/Organic.php

Some users do not have any CRON mechanism set up on their Wordpress instance, and as a result we need to be able to synchronize Content Meta data when they save and not defer it until later.

EP-2178: Add option for foreground post syncs

---

Organic/AmpAdsInjector.php
Organic/Organic.php
Organic/PageInjection.php

If the post belongs to several categories, section will be array of ~[primary_category, next_category]~ [...c1_slugs], and keywords will be merged array of ~[...rest_categories, ...tags]~ [...c2_slugs, ...c3_slugs, ..., ...tags]

EP-2126: fill in keywords and section by categories slugs

---

Organic/PageInjection.php

**Change Request:**
We need to control how much traffic Organic Ads are loaded on for initial client onboarding. One instance is when the client are still working with other Ad Stack and we want to load our ads.txt entries without rendering any ads.
1. Organic Ad traffic control with 0% traffic was breaking as the condition 
`$this->organic->getOrganicPixelTestPercent() != ''` was comparing empty string to integer. This would always result in false and not create `BVTests` object.
2. Removed redundant AB testing code which instantiated other AdStack.

EP-3358: Removing redundant ad setup call, fixing if statement condition

---

affiliate/blocks/productCarousel/src/style.scss

This isn't a pressing change, as we are still making changes to the height in [this pr](https://github.com/orgnc/platform/pull/2888). Also, this isn't a _breaking_ change, since we have a `min-height` here. So, theoretically, the block should conform to the height of the iframe set by the SDK.

EP-4511 Modify Product Carousel height

---

Organic/Affiliate.php
affiliate/blocks/productCard/src/Edit.jsx
affiliate/blocks/productCard/src/ProductCard.jsx
affiliate/blocks/productCard/src/ProductCardModal.jsx
affiliate/blocks/productCard/src/Save.jsx
affiliate/blocks/productCard/src/index.js
affiliate/blocks/productCard/src/propTypes.js
affiliate/blocks/productCarousel/src/Edit.jsx

This PR modifies the product card so that it is built using the platform widget's component rather than using separate, WordPress-specific form controls. This ensures that any changes we make to product card creation can be executed in one spot rather than having to make the changes both in the platform code (widgets page) and in the wordpress-plugin code. The PR also changes the edit icon for both the product card and the product carousel from a magnifying glass to a pencil.
Note that as soon as this PR is in production (when this PR is released and the solutions-wordpress code is updated to use the latest wordpress-plugin version), creating new product cards will be temporarily broken until https://github.com/orgnc/organic-web/pull/1486 is released. Once this organic-web PR is released, …

EP-4447: Refactor affiliate product card to use iframed product card creation widget

---

Organic/AdminSettings.php

Quick single-line cleanup. There's no indication that V2 breaks ads, but this was added early during testing and had not yet been cleaned up.

EP-3440: Remove "breaks ads" text from WP plugin settings

---

build-zip.sh

In https://github.com/orgnc/wordpress-plugin/pull/142, I added a new affiliate script that would run our SDK so that widgets displayed correctly. I tested locally, but testing on a feature PR [here](https://github.com/orgnc/solutions-wordpress/pull/3837), I realized that build-zip.sh hadn't been updated to copy the file containing the script (which, no surprises, leads to a 404 error in the console). This PR fixes the issue. I've tested locally once more, including a test with the plugin directory built via build-zip.sh to better mimic the feature/production environment.

Modify build-zip.sh to include new affiliate SDK script

---

affiliate/initSDKOnPostLoad.js

- Using `pageshow` event instead of `load` because `pageshow` is more robust (see https://developer.mozilla.org/en-US/docs/Web/API/Window/pageshow_event). I saw some threads about `load` difficulties with Firefox. (See, e.g., https://stackoverflow.com/questions/15945206/window-load-doesnt-seem-to-be-working-in-firefox.)
- Use setTimeout 0 to run the script after the JS runtime stack has been processed.

Bugfix: Get affiliate SDK reinit script working on Firefox

---

src/Organic/Affiliate.php

I should have named this branch `bugfix/...` but I didn't think it was worth creating a new branch.
In any case, this PR fixes an error in which affiliate blocks were not working properly because their dependencies were not registered correctly. See https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/javascript/js-build-setup.md#dependency-management.
Quick video showing them working again (ignore the awful styling--I was testing something else locally):
https://user-images.githubusercontent.com/47676832/230426534-446f91bf-003c-43f0-9ca2-0c949e323295.mov

EP-5061: Add affiliate block script dependencies to wp_register_script

---

.env.template
.github/workflows/integration-tests.yaml
dev.py
docker-compose.yml
src/tests/SeleniumBrowser.php
src/tests/test_affiliate/WidgetsTest.php

I've added a Selenium test to check that the user can insert an Organic Affiliate "magic" link. Brief summary:
- I created a test user with credentials shared via 1Password (Organic->Shared->Organic Login External Selenium Tests), which have been added as secrets to this repo.
- I created a [test product](https://app.organic.ly/apps/affiliate/products/7cbfc98e-ffcc-456e-ac5d-831150f43177?siteGuid=1579aae8-85e4-4ca7-b556-7b52816f529c) (for Organic Demo).
- The test itself goes to a post, selects the icon to insert and Organic link, logs into the Organic Affiliate widgets page that appears as an iframe using the test credentials, searches for and selects the test product, and then checks that the link has been inserted.
In the process, I fixed an iframe selection issue for wp59.
If this PR …

EP-5162: Add testInsertMagicLink

---

.github/workflows/integration-tests.yaml
src/Organic/PageInjection.php
src/blocks/affiliate/productCard/src/Edit.jsx
src/blocks/affiliate/productCard/src/Save.jsx
src/blocks/affiliate/productCarousel/src/Edit.jsx
src/blocks/affiliate/productCarousel/src/Save.jsx
src/blocks/affiliate/shared/WidgetToolbar.jsx
src/blocks/affiliate/shared/helpers.js

Somehow the `pageshow` event is being triggered too early in some cases; setting a higher timeout fixed the issue, but that's obviously a hack.
I feel doubtful about finding the "right" event to guarantee that WordPress has fully "loaded" if `pageshow` fails; instead, it feels safer to reference WordPress functionality directly. This alternative solution is based on https://gist.github.com/KevinBatdorf/fca19e1f3b749b5c57db8158f4850eff. (https://github.com/WordPress/gutenberg/issues/8379 was also helpful.)
https://github.com/orgnc/wordpress-plugin/assets/47676832/a43af454-3578-426a-96ff-b11d4e3abaee

EP-5546: Widget Insertion Refresh Part 2

---

src/Organic/AdminSettings.php
src/Organic/PageInjection.php

Flying Mag looks like they use a custom post type (example URL: https://dev.flyingmag.com/wp-admin/edit.php?post_type=guides). Because of this, the SDK is not loaded on such posts: https://github.com/orgnc/wordpress-plugin/blob/296b81805f24a9a750129091071b43ffb70b85c9/src/Organic/PageInjection.php#L141-L154
This means that widgets are not loaded properly. (😭 not again!)
I've added the "guides" post type as a temporary workaround, and I've confirmed this resolves the issue on the Flying Mag dev site. But this probably shouldn't be hard-coded at all. I think we should just use similar logic as we do in the Admin Settings (e.g., https://github.com/orgnc/wordpress-/blob/296b81805f24a9a750129091071b43ffb70b85c9/src/Organic/AdminSettings.php#L512). I'm not sure we want a separate option, like …

Add Admin SDK injection for "guides" post type

---

.github/workflows/code-quality.yaml
.github/workflows/dev-release.yaml
.github/workflows/release.yaml
src/composer.json
src/composer.lock

Install correct versions of PHP and composer globally
The previous approach used correct versions only during `composer install` step
https://github.com/php-actions/composer/issues/67#issuecomment-1005187924

Use correct versions of PHP and composer in GH-actions

---

src/composer.json
src/composer.lock
src/readme.txt

This is only a temporary measure. The long term plan is to use something like PHP Scoper to avoid any clashes between library versions. See EP-5792 for more details

Bugfix: Lock sentry versions for compatibility with WP Sentry

---

src/Organic/AdminSettings.php
src/Organic/ContentSyncCommand.php
src/Organic/Organic.php
src/Organic/SDK/OrganicSdk.php
src/Organic/helpers.php

The primary issue fixed here is the OrganicSDK. We were previously missing an intermediary array key for `syncWordpressPluginConfig` which is now included.
Through the course of debugging this issue, I added some minor code restructuring that I'm leaving in this PR with other minor fixes/optimizations.

Bugfix: config sync content sync

---

src/blocks/affiliate/shared/integrationModal.scss

This PR fixes an issue where the Organic Affiliate WP modal contains an extraneous `<div>` that prevents the iframe from spanning 100% height, thus rendering it unusable.

EP-6140: Fix Organic Affiliate modal height issue

---

src/Organic/AdminSettings.php

This PR removes the "WARNING: DO NOT USE IN PRODUCTION" message that's very, very obsolete.

Remove obsolete messaging from WP settings
